### ISSUE TITLE
Incompatible with VS code version 1.41.1

### ISSUE THREAD

**Issue by penguin-boxx** [bash-spbu/vscode-lama-language#1]
Thank you for the extension! 

Do not work with this vscode version:

![Screenshot_2020-03-03_01-01-50](https://user-images.githubusercontent.com/25281147/75722150-b19a3f00-5cea-11ea-8808-8367bdc12084.png)

**Comment by bash-spbu** [comment]
Oops, auto-generated package provider has had the greatest version of the VSCode, namely "1.42.0" as a lower bound. I have lowered it to "1.30", should be enough.

Now your VSCode should suggest to install this plugin automatically (on opening .lama file) or, if it does not, you can get it from [marketplace](https://marketplace.visualstudio.com/items?itemName=bashspbu.lama-language)

You are welcome :)
